---
- name: Remove previous tflint version
  ansible.builtin.file:
    path: "{{ terraform_tflint_install_basedir }}"
    state: absent
  become: true
  when: terraform_tflint_remove_previous_versions

- name: Remove previous tfsec version
  ansible.builtin.file:
    path: "{{ terraform_tfsec_install_basedir }}"
    state: absent
  become: true
  when: terraform_tfsec_remove_previous_versions

- name: Download tflint
  ansible.builtin.get_url:
    dest: /tmp
    url: "{{ terraform_tflint_url }}"
    checksum: "{{ terraform_tflint_checksum }}"
    mode: "u=rwx,go=rx"
  register: tflint_download
  when: terraform_tflint_install
  changed_when: false

- name: Create tflint installation dir
  ansible.builtin.file:
    path: "{{ terraform_tflint_install_path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "u=rwx,go=rx"
  become: true

- name: Extract tflint archive
  ansible.builtin.unarchive:
    src: "{{ tflint_download.dest }}"
    dest: "{{ terraform_tflint_install_path }}"
    remote_src: true
  when: terraform_tflint_install
  become: true

- name: Create tflint symlink
  ansible.builtin.file:
    src: "{{ terraform_tflint_install_path }}/tflint"
    dest: "{{ terraform_tflint_bin }}"
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Create tfsec installation dir
  ansible.builtin.file:
    path: "{{ terraform_tfsec_install_path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "u=rwx,go=rx"
  become: true

- name: Download and install tfsec
  ansible.builtin.get_url:
    dest: "{{ terraform_tfsec_install_path }}/tfsec"
    url: "{{ terraform_tfsec_url }}"
    checksum: "{{ terraform_tfsec_checksum }}"
    mode: "u=rwx,go=rx"
  register: tfsec_download
  when: terraform_tfsec_install
  become: true

- name: Create tfsec symlink
  ansible.builtin.file:
    src: "{{ terraform_tfsec_install_path }}/tfsec"
    dest: "{{ terraform_tfsec_bin }}"
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Clean up downloaded files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tflint_download.dest }}"
  changed_when: false
