---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include Distribution-specific variables (Amazon Linux)
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Amazon'

- name: Import key (APT)
  ansible.builtin.get_url:
    url: "{{ hashicorp_repository }}/gpg"
    dest: "{{ hashicorp_keyring }}"
    mode: '0644'
    force: true
  become: true
  when: ansible_os_family == 'Debian'

- name: Disable hashicorp repository not using keyring (APT)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] {{ hashicorp_repository }} {{ ansible_distribution_release | lower }} main"
    filename: hashicorp
    state: absent
  become: true
  when: ansible_os_family == 'Debian'

- name: Enable hashicorp repository (APT)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ hashicorp_keyring }}] {{ hashicorp_repository }} {{ ansible_distribution_release | lower }} main"
    filename: hashicorp
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Enable hashicorp repository (Yum)
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp repository
    state: present
    baseurl: "{{ hashicorp_repository }}/{{ hashicorp_rpm_family }}/$releasever/$basearch/stable"
    gpgkey: "{{ hashicorp_repository }}/gpg"
    gpgcheck: yes
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install terraform
  ansible.builtin.package:
    name: terraform
    state: present
  become: true

- name: Include extras
  ansible.builtin.include_tasks: ./install_extras.yml
