---
- name: Converge
  hosts: all
  roles:
    - role: ecgalaxy.common_packages
    - role: terraform
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
