---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include role defaults vars
      with_first_found:
        - "../../defaults/main.yml"
      ansible.builtin.include_vars: "{{ item }}"
    - name: Check terraform binary file
      ansible.builtin.stat:
        path: /usr/bin/terraform
      register: bin
    - name: Assert that terraform binary is installed
      ansible.builtin.assert:
        that:
          - "bin.stat.exists"
    - name: Check terraform execution
      ansible.builtin.command: terraform -version
      register: output
    - name: Assert that terraform is installed
      ansible.builtin.assert:
        that:
        - "'Terraform' in output.stdout"
    - name: Check tflint binary file
      ansible.builtin.stat:
        path: "{{ terraform_tflint_install_path }}/tflint"
      register: bin
    - name: Assert that tflint is installed
      ansible.builtin.assert:
        that:
          - "bin.stat.exists"
    - name: Check tflint execution
      ansible.builtin.command: tflint --version
      register: output
    - name: Assert that tflint is installed
      ansible.builtin.assert:
        that:
        - "'TFLint version {{ terraform_tflint_version }}' in output.stdout"
    - name: Check tfsec binary file
      ansible.builtin.stat:
        path: "{{ terraform_tfsec_bin | dirname }}/tfsec"
      register: bin
    - name: Assert that tfsec is installed
      ansible.builtin.assert:
        that:
          - "bin.stat.exists"
    - name: Check tfsec execution
      ansible.builtin.command: tfsec --version
      register: output
    - name: Assert that tfsec is installed
      ansible.builtin.assert:
        that:
        - "'{{ terraform_tfsec_version }}' in output.stdout"
